version: '3'
services:
  app:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: e18b6b0bcbd25bc2bdf7b09f20070e9b
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pkpadmin
      POSTGRES_PASSWORD: param22
      POSTGRES_DB: clinic_app_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
