default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pkpadmin
  password: param22
  host: localhost

development:
  <<: *default
  database: clinic_app_development

test:
  <<: *default
  database: clinic_app_test

production:
  <<: *default
  database: clinic_app_production
  username: clinic_app
  password: <%= ENV['CLINIC_APP_DATABASE_PASSWORD'] %>
